library(GRANBase)
man = GithubManifest("gmbecker/rpath", "gmbecker/fastdigest")

##repo = makeSingleGRANRepo(manifest = man@manifest, subRepoName = "current", baseDir = "~/tempRepos", dest_base = "~/tempRepos", dest_url = paste0("file:///home/beckerg4/tempRepos"))
Rprof("firstbuild.Rprof")
repo = makeRepo(man, repo_name = "current", basedir = "~/tempRepos")
Rprof(NULL)
Rprof("secondbuild.Rprof")
repo2 = makeRepo(repo)
Rprof(NULL)

bld1 = summaryRprof("firstbuild.Rprof")
bld2 = summaryRprof("secondbuild.Rprof")
save(bld1, bld2, file ="profsummaries.rda")
repo2 = makeSingleGRANRepo(repo = repo2, subRepoName = "current")
